### ISSUE TITLE
General question about flow and models

### ISSUE THREAD

**Issue by gbkwiatt** [node-oauth/node-oauth2-server#115]
Well,  I've got that brilliant idea to spin my own oauth2 server ;).
My Idea is so I can use it for my multiple project without needing to implement the whole logic for each API like I did before. 
To the point: 

Currently I only want 2 grants, `client_credentials` and `password`.
So `password` grant will be for users to register and obtain token, with lets say `scope: user` 
and for that I will only use `token()` method, with refresh token etc. 

However to have users I need to be able to register them, so I want my other APIs to have their own `clientId` and `clientSecret` and with that, obtain token with `client_credentials` and `scope: registration`  and only accessToken.

Then in my oauth2 server I have endpoint protected with `oauth.authenticate()` - so far so good. 

But I also decided to create JWT tokens instead as an accessToken. 
So Questions: 
1. Do I have to validate token in `getAccessToken` myself, since I can see option to override `validateAccessToken` of oauth2 server ?
1.1 I know, technically I don't have to validate token, since it's compared with the one in db so it "must" be correct and with correct expiration date, so is that a good practice to validate token against public key anyway ? 
2.  I am bit confused about scopes, when accessing my protected routes after  `oauth.authenticate()`  it basically is enough if token is not expired, but what about scope ? 
3. What's the best way to validate token for the user `password` grant ? e.g. when in my API I have protected user routes, I will have to ask oauth-server each time to confirm token is still valid and for valid user or something like that ? Is it basically like above(2), having protected route with `authenticate()` scope `user` ? 

I know it might al sound trivial, but I am really determine to implement oauth2 correctly without bypassing some security requirements etc.

**Comment by jorenvandeweyer** [comment]
1. Verifying the JWT is secure enough, you should not necessarily check the existence of the token in your oauth2 server database. Personally I'd not save the access token if you are creating a multitenant oAuth2 server. _(This means once an access token is issued you can not easily revoke it. Therefore you should give your access tokens a short lifetime or implement some other ways to support token revocation.)_
2. With a scope you can limit the accessibility of certain token pair. You can create a token with a `read_only` scope and your application can validate with some middleware against this scope to only allow `GET` calls for example.
3. Popular oAuth2 providers also use JWT tokens, this way you don't have to contact the oAuth2 server each time a request is made to your server. You can instead validate the JWT token with a public key on your app server.
