### ISSUE TITLE
b64 regex token checks

### ISSUE THREAD

**Issue by jankapunkt** [node-oauth/node-oauth2-server#127]
@jorenvandeweyer [commented](https://github.com/node-oauth/node-oauth2-server/pull/105/files#r771944545) on pr #105:

> In the spec it is defined as it should start with Bearer followed with a whitespace. That's what the additional ^ in the regex is for. I think we should not support BeArEr @Uzlopak

b64token    = 1*( ALPHA / DIGIT /
                  "-" / "." / "_" / "~" / "+" / "/" ) *"="
credentials = "Bearer" 1*SP b64token

> But I do like the check provided for the second part. But that should be a different issue/pull request. Because that check should also be done on the result of generateAccessToken and generateRefreshToken.

**Comment by jankapunkt** [comment]
Does it make sense to implement this here: https://github.com/node-oauth/formats ?

**Comment by jorenvandeweyer** [comment]
The correct regex would be `^Bearer\s[0-9a-zA-Z-._~+/]+=*$`
