### ISSUE TITLE
4.2.0 milestone

### ISSUE THREAD

**Issue by manian-kumaran** [node-oauth/node-oauth2-server#149]
Hi,

I noticed high activity at the end of 2021, and it stoped with 4.1.1 in Nov 2021 since then. Is this fork still maintained, and is there plan to release minor or major 4.2.0 version?

I want to use this node oauth2 server but I'm worried if the fork becomes unmaintained like its parent https://github.com/oauthjs/node-oauth2-server

**Comment by jankapunkt** [comment]
Hi @manian-kumaran yes we are still active. Currently things went good and stable which we had no pressure to release a newer version. I am moving things forward. Is there something in particular in 4.2.0 that you require?

**Comment by manian-kumaran** [comment]
@jankapunkt Thank you.

It's good to know it's active and stable. I was more concerned since this package is for security and its parent is not actively maintained. I also read that this 4.1.1 contains bug fixes of the parent that was not released for a long time.

So, I'm quite happy to hear that this forked is actively maintained. I don't need anything particular or new features in 4.2.0. In fact, IMHO, for a security package, the less new features with breaking changes, the better. I prefer stability over new features.

Thanks.
