### ISSUE TITLE
`refreshToken` and `refreshTokenLifetime` is undefined when generating accessToken

### ISSUE THREAD

**Issue by Manokii** [node-oauth/node-oauth2-server#159]

**Comment by jankapunkt** [comment]
Hi @Manokii thank you for the issue. Please add some more information:

Which version do you use?
Which workflow is affected?

**Comment by Manokii** [comment]
I just read the docs, https://www.rfc-editor.org/rfc/rfc6749#section-4.4.3

I thought client_credentials grant are given refresh token, please disregard this issue
