### ISSUE TITLE
Add badges to README

### ISSUE THREAD

**Issue by jankapunkt** [node-oauth/node-oauth2-server#163]
We need the following badges:

- the following actions workflow badges:
  - https://github.com/node-oauth/node-oauth2-server/actions/workflows/tests.yml
  - https://github.com/node-oauth/node-oauth2-server/actions/workflows/codeql-analysis.yml
  - https://github.com/node-oauth/node-oauth2-server/actions/workflows/tests-release.yml
- repostatus.org "active" badge (indicating this is an active repo)
- shields.io version
- shields.io npm downloads/week
- shields.io license badge

The badges should be placed like so:

> Complete, compliant and well tested module for implementing an OAuth2 server in [Node.js](https://nodejs.org/).

**Badges here**

> NOTE: This project has been forked from...

Please use the "markdown" versions of the badges, not html or others.

**Comment by ashutosh7i** [comment]
i can do this, please assign it to me

**Comment by jmakhack** [comment]
Hey, I'd love to work on this issue. Can it be assigned to me if it is still available?

**Comment by jankapunkt** [comment]
@jmakhack go for it
