### ISSUE TITLE
TypeScript rewrite

### ISSUE THREAD

**Issue by RedstoneWizard08** [node-oauth/node-oauth2-server#174]
I'm currently rewriting this in TypeScript, and I will submit a PR when I'm done. I think that a TypeScript rewrite would be a great step in stability and dev-experience, since it would support generics, inheritance, and a bunch more features. (Goodbye, `util.inherits()`!)

This would solve:
- Issue #70

**Comment by jankapunkt** [comment]
On hold until we have discussed this.

**Comment by lohart13** [comment]
Is this something that is still being considered?

As a sub part of the migration to typescript, have you considered changing to use [ECMAScript modules](https://nodejs.org/api/esm.html) (esm)?
CommonJS (cjs) can still be supported by using a transpiler such as babel or webpack, and if migrated to typescript, this can be down with the typescript package as part of the build process.

**Comment by jankapunkt** [comment]
Hi @lohart13 we definitely consider Typescript in the long run. Regarding esm, I'm not sure if it's beneficial, since it's one more rewrite and I would like to avoid a hard dependency to a specific bundler.

**Comment by lohart13** [comment]
Ok, I have recently written a similar version of oauth2-server in typescript for another project, do you want me to submit this as a PR?

Out of interest, would this be in scope for v5 or a future release?

**Comment by jankapunkt** [comment]
@lohart13 thanks but we currently have a pending PR for a TS rewrite but it's blocked since at least I still have not enough typescript skills to do a sufficient review. However, this is definitely on my agenda as it's required for another project, too.

Maybe you could take a look into the pending TS rewrite PR and leave some comments.

**Comment by jorenvandeweyer** [comment]
A TypeScript rewrite is definitely on the roadmap. This would be in the scope of v5 since we are converting a lot of stuff to ES6+ see #212 

We'll be accepting PR's after v5 has been published. Closing for now.
