### ISSUE TITLE
State of this project?

### ISSUE THREAD

**Issue by shrihari-prakash** [node-oauth/node-oauth2-server#182]
Since past 6 months, I had been using [oauthjs/node-oauth2-server](https://github.com/oauthjs/node-oauth2-server) to extend create my own user management framework called [Liquid](https://github.com/shrihari-prakash/liquid) on top of it. 

However, it was only yesterday that I noticed that the project hasn't gotten updates for quite some time now. It's pretty bad to find the README say that the project is back under active maintenance and the conversations in issues say the opposite. 

I know this project is still starting from zero from a visibility point of view, but should I use this in my project? Or do you intend to discontinue support for this project sometime? If you do not wish to continue support, do you know any closest alternatives?

**Comment by jankapunkt** [comment]
Hi @shrihari-prakash we are still active on this one, however we got a pretty stable state right now so further development slowed down a bit. If there is an urgent issue or bug feel free to report and don't hesitate to open a PR if appropriate.

**Comment by shrihari-prakash** [comment]
Thanks for confirming @jankapunkt . Is there a counterpart for https://github.com/oauthjs/express-oauth-server available for this one yet?

**Comment by shrihari-prakash** [comment]
@jankapunkt found this fork that uses the new oauth2-server: https://github.com/node-oauth/express-oauth-server, but I've not been able to find it on npm. Am I missing something?

**Comment by jankapunkt** [comment]
Might not be published since we haven't reviewed it. I can try to update and publish an rc which you could review. What do you think?

**Comment by shrihari-prakash** [comment]
Sounds perfect :) Would be available for any help to improve this eco system. @jankapunkt

**Comment by shrihari-prakash** [comment]
@jankapunkt , I know ETAs are irritating. I'm not going to ask that. But would this be worked upon in the near future?

**Comment by jankapunkt** [comment]
@shrihari-prakash I can't say as I personally don't use an express implementation so I am not the best person to review things.

@Uzlopak @HappyZombies @jorenvandeweyer  is there one of you guys using the express adapter?

By the way there is an open PR that updated a few things: https://github.com/node-oauth/express-oauth-server/pull/6

Anyone checked on that?

**Comment by HappyZombies** [comment]
I use the project in express but not with the express wrapper, since I found my use case for it rather limiting.

Tbh I would honestly encourage to not use an express wrapper but that's just me 🤷‍♂️.

Not sure when/if I can take a look at the express wrapper as a whole but I'll see the MR 👍

**Comment by shrihari-prakash** [comment]
@HappyZombies do you have an example or a sample implementation connecting this with express?

**Comment by shrihari-prakash** [comment]
Hello @HappyZombies ,
Thanks much for this! Let me try this on my side and get back. On a side note, I think it would be good if we include such examples for important connectors like express inside this repo and link it on the readme so getting started with this project would be much more developer friendly 🙂

**Comment by HappyZombies** [comment]
Yup, I hope to get some examples done...one day lol, but true that once those are ready I can link them in the README for sure 👍

**Comment by shrihari-prakash** [comment]
@HappyZombies , @jankapunkt 

Let me know if you'd like me to send a PR to include some example files.

**Comment by shrihari-prakash** [comment]
@HappyZombies I was able to migrate my application to this package. Thanks for the samples.🙂

**Comment by Uzlopak** [comment]
I wanted to implement a standalone oidc provider in fastify based on the experience I gained by this project. 

I even created a github org and reserved a domain for that. 

https://www.cthulhu-oidc.dev/

But well... I have no time.

**Comment by shrihari-prakash** [comment]
@jankapunkt @HappyZombies ,

I created a sample express implementation of this package in https://github.com/shrihari-prakash/oauth-express-example, could you consider linking it to the readme of this repository?

**Comment by jankapunkt** [comment]
@shrihari-prakash I'd rather like to get our express adapter to be up2date and published. @HappyZombies any idea how we can make an actionable plan to get to this state?

**Comment by shrihari-prakash** [comment]
Will test this later today with my project and let you know.

**Comment by HappyZombies** [comment]
@jankapunkt what do you mean? Are you saying you'd like an example express app with the adapter. Or you want to update/refactor the adapter?
