### ISSUE TITLE
Remove promisify-any dependency

### ISSUE THREAD

**Issue by jwerre** [node-oauth/node-oauth2-server#20]
Just use [`util.promisify`](https://nodejs.org/docs/latest-v14.x/api/util.html#util_util_promisify_original)

**Comment by jwerre** [comment]
Just realized Bluebird is a [dependency](https://github.com/overlookmotel/promisify-any/blob/f6447d6f143e8d6a0aa9dd71447f885b5d715904/package.json#L17) of promisify-any. Removing this should probably come before removing [Bluebird](https://github.com/node-oauth/node-oauth2-server/issues/19).

**Comment by jankapunkt** [comment]
Also here let's check if tests already cover these cases / functionality enough in order to be on the safe side. I think coverage is very high but there are a few lines missed and you know how Mr. Murphy thinks about this :-)

**Comment by jankapunkt** [comment]
I think we can start on this after #30 has been merged

**Comment by jwerre** [comment]
I'm looking into this now and noticed some oddities I thought maybe you guys could chime in on. First off, a lot of the tests are returning the wrong value, [here](https://github.com/node-oauth/node-oauth2-server/blob/b1676fb8a2f7f8d5ff71d7c926bb0901dce54d34/test/unit/grant-types/abstract-grant-type_test.js#L19) `generateAccessToken` should [return a string](https://oauth2-server.readthedocs.io/en/latest/model/spec.html#generateaccesstoken-client-user-scope-callback). For example:

```js
generateAccessToken: sinon.stub().returns({ client: {}, expiresAt: new Date(), user: {} })
```

should be:

```js
generateAccessToken: sinon.stub().returns('my-access-token')
```

I believe these were left over from version 2 and never updated.

Second, I'm not sure `util.promisify` is going to work since it requires a callback function and all the of the methods I looked at don't even have a callback as an argument. We could wrap everything in a `new Promise` but that could get pretty messy.

You guys have any thoughts on this? How to promisify this:

```js
AbstractGrantType.prototype.generateAccessToken = function(client, user, scope) {
  if (this.model.generateAccessToken) {
    return promisify(this.model.generateAccessToken, 3).call(this.model, client, user, scope)
      .then(function(accessToken) {
        return accessToken || tokenUtil.generateRandomToken();
      });
  }

  return tokenUtil.generateRandomToken();
};
``` 

I initinally thought we could do this but it won't work since there is no callback:

```js
AbstractGrantType.prototype.generateAccessToken = function(client, user, scope) {
  if (this.model.generateAccessToken) {
    return require('util').promisify(this.model.generateAccessToken)(client, user, scope)
      .then(function(accessToken) {
        return accessToken || tokenUtil.generateRandomToken();
      });
  }

  return tokenUtil.generateRandomToken();
};
```

**Comment by jankapunkt** [comment]
Yes I ran the tests right now with `util.promisify` and they all fail due to what you wrote @jwerre 

If the functions are simple one-dimensional we could write our own wrapper like so:

```
const promisify = fn => function (...args) {
  const env = this;
  return new Promise((resolve, reject) => {
    try {
      resolve(fn.call(env, ...args));
    } catch (e) {
      reject(e);
    }
  });
};
``` 

I checked a few tests and it works so far but I am not sure if this works for all.

**Comment by jankapunkt** [comment]
@jwerre did you come up with anything? Maybe you open a draft pull request so we can work out the details using the code review?

**Comment by jwerre** [comment]
@jankapunkt @HappyZombies, what would you guys say to removing support for callbacks all together?

**Comment by jankapunkt** [comment]
I agree with @HappyZombies buy I will still take a look into it. In the meantime we can further discuss release management

**Comment by Uzlopak** [comment]
I also had a look into promisify-any. promisify-any is capable of wrapping also generator functions. 

Is there any necessity to support generator functions?
