### ISSUE TITLE
generateAuthorizationCode not being awaited

### ISSUE THREAD

**Issue by MaximilianGaedig** [node-oauth/node-oauth2-server#204]
generateAuthorizationCode is not being awaited and when I use the authorizationCode in my model it errors because its a promise and not a string, pr: #203
This is a very important issue to fix because if someone follows the types and implements the model correctly it just crashes and doesn't work at all
Workaround: await authorizationCode in the models saveAuthorizationCode function

**Comment by jankapunkt** [comment]
Hi @MaximilianGaedig I can confirm your observation and thanks a lot for immediately opening a PR, too! I would like to investigate, why the tests never catched this one, before merging.

**Comment by jankapunkt** [comment]
published in https://github.com/node-oauth/node-oauth2-server/releases/tag/v5.0.0-rc.1

**Comment by MaximilianGaedig** [comment]
Thanks a lot for this quick handling of the issue/pr!
