### ISSUE TITLE
TypeScript: Remove callback from types in 5.x

### ISSUE THREAD

**Issue by jankapunkt** [node-oauth/node-oauth2-server#210]
In release 5.x (#194)  we dropped all callbacks, so types should reflect that, too. PR should target only `release-5.0.0`

**Comment by jankapunkt** [comment]
@shrihari-prakash did you mean "review"?

**Comment by shrihari-prakash** [comment]
Haha yes :)

**Comment by jankapunkt** [comment]
All changes are now public at https://node-oauthoauth2-server.readthedocs.io/en/latest/?badge=latest
