### ISSUE TITLE
Move all ES5 style classes into ES6+ style class

### ISSUE THREAD

**Issue by jankapunkt** [node-oauth/node-oauth2-server#212]
Targeting release 5.0.0 we should complete the ES6+ migration by transforming all ES5-style classes into ES6+ style `class` constructs.

This currently applies to the following classes:

- [x] AbstractGrantType #227 
- [x] BearerTokenType #227 
- [x] MacTokenType #227 
- [x] AuthenticateHandler  #227
- [x] AuthorizeHandler  #227
- [x] TokenHandler  #227
- [x] TokenModel #223
- [x] CodeResponseType #225
- [x] TokenResponseType #225
- [x] Request #225
- [x] Response #225
- [x] OAuth2Server #227

**Comment by jorenvandeweyer** [comment]
@jankapunkt In your issue you said that these PR's should be targeted for the 5.0.0 release.

I'm a bit confused because #223 was merged in development.

Is the development branch for future 4.x releases and if so how are we keeping `release-5.0.0` and `development` in sync?

**Comment by jankapunkt** [comment]
@jorenvandeweyer sorry my mistake, development is correct as we will merge development and 5.0.0 anyway
