### ISSUE TITLE
getClient called with non-decoded secret/client

### ISSUE THREAD

**Issue by MaximilianGaedig** [node-oauth/node-oauth2-server#213]
Here getClientCredentials takes request.body.client_id and request.body.client_secret without calling decodeURIComponent() on them:
```js
// token-handler.js
TokenHandler.prototype.getClientCredentials = function(request) {
  [...]
  if (request.body.client_id && request.body.client_secret) {
    return { clientId: request.body.client_id, clientSecret: request.body.client_secret };
  }
 [...]
};
```
The result of this is not the client secret arriving at the getClient method, but the url encoded version of it, which in my case was base64 encoded so it was changed and the getClient method failed.

I think handling it in the model is not problematic but unnecessary so it should be done in the library

### "Workaround"
```ts
class Model {
  async getClient(clientId: string, clientSecret: string | null): Promise<Client | Falsey> {
    const clientIdDecoded = decodeURIComponent(clientId);
    const clientSecretDecoded = clientSecret ? decodeURIComponent(clientSecret) : null;
    // use clientIdDecoded and clientSecretDecoded in your database logic instead of clientId and clientSecret
  }
}
```

**Comment by jankapunkt** [comment]
Hi @MaximilianGaedig since the encoding if entirely part of the surrounding implementation so does the decoding. We can't make any assumptions beyond the standard, which is why the model is one place where this should be done.

However, note, that your token endpoint could also be a place to handle such.

```js
const server = new OAuth2Server({ model })

// ...other endpoints

// this could be added to express or other middleware
const tokenEndpoint = function (req, res, next) {
  const { clientSecret } = req.body
  req.body.clientSecret = clientSecret ? decodeURIComponent(clientSecret) : null;

  const request = new Request(req)

  server.token(request, response, options)
        .then(function (code) {
          // ...
        })
        .catch(function (err) {
          // ...
        })
}
```

**Comment by MaximilianGaedig** [comment]
Ah okay, maybe documenting it would be a good idea, like including a notice by the getClient method

**Comment by jankapunkt** [comment]
@MaximilianGaedig sure, I'm adding this to #208
