### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by jwerre** [node-oauth/node-oauth2-server#22]
The barrier to entry on this package isn't insurmountable but it's not easy either. I'd love to see some examples using the following databases:

- SQL
- MongoDB
- Redis

**Comment by jankapunkt** [comment]
I am using it with Mongo but not mongoose as we use it for a Meteor project and I created a Meteor package with integration for this project which I could link in examples, too. If there is time and we have sorted out things I could work on a node/express/mongo/mongoose example

**Comment by HappyZombies** [comment]
I can provide a solid MySQL example as well.

**Comment by HappyZombies** [comment]
We will move discussions to examples over here https://github.com/node-oauth/node-oauth2-server-examples
