### ISSUE TITLE
PR #197 fix removed after merge

### ISSUE THREAD

**Issue by mthlemos** [node-oauth/node-oauth2-server#258]
**Specify your setup**

- Operating System: macOS Sonoma 14.1
- Node version: 18.12.1
- npm version: Not applicable
- version of @node-oauth/oauth2-server: `release-5.0.0` branch
- which [OAuth2 workflow](https://datatracker.ietf.org/doc/html/rfc6749.html#section-1.3): Authorization Code
- at [which workflow step](https://datatracker.ietf.org/doc/html/rfc6749.html#section-1.2) does the error occur: Authorization Request

**Describe the bug**

PR #197 fix got removed after a merge commit.

More specifically this merge commit: 6758bffe4e53979ad86ad908c5f671002dcfe9e2

**To Reproduce**

This bug is currently present on the `release-5.0.0` branch.

https://github.com/node-oauth/node-oauth2-server/blob/b97f6c773cecca3563b0b39c7179ed813d006c4f/lib/handlers/authorize-handler.js#L370

https://github.com/node-oauth/node-oauth2-server/blob/b97f6c773cecca3563b0b39c7179ed813d006c4f/lib/handlers/authorize-handler.js#L381

**Expected behavior**

Should also receive the `code_challenge` and `code_challenge_method` through the query params.

```javascript
getCodeChallenge (request) {
  return request.body.code_challenge || request.query.code_challenge;
}
```

```javascript
getCodeChallengeMethod (request) {
  const algorithm = request.body.code_challenge_method || request.query.code_challenge_method;
  ...
}
```

**Additional context**

None

**Comment by jankapunkt** [comment]
@mthlemos added this again in https://github.com/node-oauth/node-oauth2-server/releases/tag/v5.0.0-rc.5 feel free to reopen if the issue persists in rc5

**Comment by mthlemos** [comment]
Thank you very much for the quick fix @jankapunkt!
