### ISSUE TITLE
v5.1`AuthorizationOptions.scope`Breaking Change

### ISSUE THREAD

**Issue by Lordfirespeed** [node-oauth/node-oauth2-server#307]
related: #305, #306

Version 5.1 changed the accepted type of `AuthorizationOptions.scope` from `string[]` to `string`, which is a breaking change.

**Comment by dhensby** [comment]
introduced in #267 

The only sensible approach is to accept both strings and arrays of strings for this argument.

**Comment by Lordfirespeed** [comment]
Resolved by #309

**Comment by jankapunkt** [comment]
Will publish this with a new minor release, once we got #314 merged.
