### ISSUE TITLE
Release strategy

### ISSUE THREAD

**Issue by jankapunkt** [node-oauth/node-oauth2-server#36]
How do we want to release a new version?

- who should release? -> human vs GitHub Actions?
- when to release?
- how to prepare a release? -> one `release` branch with tags or one branch for each major version? like `release-4.x`, `release-5.x`
- do we want additional tests that run in GitHub actions when merging to a release branch? GH Actions is so flexible I could even clone another repo and install the intended release package into it and run tests, so we can test adapter-compliance and even the example repo if we want. There are no limits :-)
- who is responsible for release management and the deployment keys, npm repo etc.?
- do we also want to release to GitHub packages as a redundancy factor?
- what else....?
- do we want to hold these information in a `MAINTAINERS.md? ?

**Comment by oklas** [comment]
Excellent considerations. I would be glad to work on this and continue developing the release process based on the commit message (the ideas that I suggested in #32).

**Comment by jankapunkt** [comment]
@HappyZombies can you add @oklas to the maintainers? I unfortunately can*t

@oklas that would be great! Are you familiar with dependabot and github actions? I am so half-half (used both in my projects and read the docs but skipped many sections that I thought irrelevant at that time). I think we can make huge progress just by getting to know how both actually work:

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

**Comment by jwerre** [comment]
> (if I am being honest I took a risk with adding you both and I don't wanna keep taking risks lol)
🤣

**Comment by jankapunkt** [comment]
@HappyZombies allright no problem I can totally understand this it's all risky for all of us involved (at least when running this in production)

Well, then let's first go through the proposed release strategy and see if you and @jwerre have any further thoughts on this.

**Comment by oklas** [comment]
"Just write PR" can only be done for just code and tests. Working on things like config and interacting with third party services tuned to a specific repository or branch requires access to the repository and branch and third party services. Therefore, the first way is to set up a similar complex of systems in another repository, which means not just a fork, but a complex of interconnected systems. And the second way is a membership, which @jankapunkt suggested. And of course, permanent work is much more convenient and efficient from the inside.

**Comment by HappyZombies** [comment]
Closing since we are done here and also due to #121
