### ISSUE TITLE
Update crypto hash to use sha256 

### ISSUE THREAD

**Issue by HappyZombies** [node-oauth/node-oauth2-server#38]
This line in [token-utils](https://github.com/node-oauth/node-oauth2-server/blob/master/lib/utils/token-util.js#L23).

Uses `sha1` for the hash, we should update this to be sha256 and update our unit tests too.

**Comment by jwerre** [comment]
Yes! nice find @HappyZombies

**Comment by jwerre** [comment]
This [line](https://github.com/node-oauth/node-oauth2-server/blob/b9aae53a8385417bb5b613c801b05bdcd7e3f9d3/test/assertions.js#L16) will need to change to: `new chai.Assertion(obj).match(/^[a-f0-9]{64}$/i);`
