### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by oklas** [node-oauth/node-oauth2-server#40]
We need to run the documentation. We can use the free `js.org` domain on this stage, for example, obviously:

```
node-oauth.js.org
```

I have experience to set it up it for my open source projects, along with the GitBook documentation engine. Both also used by the well-known Redux (or at least Redux used GitBook before did not check for now). Thereat it was easy, but now I would prefer to use something more interesting. Most likely including but not limited to JSDoc which is mentioned in the discussion #5

**Comment by jankapunkt** [comment]
I could help by setting up JSDoc and make sure we have a good documentation coverage

**Comment by HappyZombies** [comment]
This sounds like a great idea, but I really think we have other priorities right now. There's no reason to get these docs up and running ASAP, when we haven't even introduced new and/or breaking changes. For the time being we can link the docs to the old repo.

**Comment by HappyZombies** [comment]
Closing in favor of #118
