### ISSUE TITLE
Code Quality

### ISSUE THREAD

**Issue by jankapunkt** [node-oauth/node-oauth2-server#5]
Some things I'd like to discuss and also work on is code quality and documentation:

- Tests and coverage (mocha, chai, sinon, istanbul)
- Linter
- API Docs
- Wiki, if desired
- README and badges
- GitHub Actions for CI and CD
- static analysis like semmle / lgtm for non-dependency vulnerabilities: https://github.com/node-oauth/node-oauth2-server/security/code-scanning
 
There are a few things to decide, like 

- what linter do we want to use (I suggest something with zero config like prettier or standard)
- what doc generation (JSDoc) we want to use (I suggest also zero config like JSDoc)
- should `master` / `main` be push-protected?
- what should be required for CI to pass a basic pull request?
  - linter?
  - unit tests?
  - minimal required test coverage?
  - dependency audit via npm audit?
  - security analyses?

What else?

**Comment by jankapunkt** [comment]
**Mergining strategy**

I think the branching is good, we should always release into `release` so we can have CI run extra integration tests with all adapters before publishing. Dev can run only standard tests.

**GitHub Action**

I have experience with GH Actions and can provide a PR.

**Linter** 

I have no experience with linter and typescript so maybe someone else who is more experienced in this combo starts a PR?

**Static Analysis**

Yes I'm good with that

**API Docs**

I can provide a PR later

**Readme and badges and wiki**

let's focus on that later

**Comment by HappyZombies** [comment]
Sounds good, I will clean up the dev branch and add protection to master so no one can push directly. 

Sadly we lose whatever was on dev but worse case we just look at the old dev branch from the original repo.

**Comment by HappyZombies** [comment]
@jankapunkt should development be the default branch? I feel like doing so would kinda make master redundant...which then begs the question of why even have a development branch 🤷

**Comment by jankapunkt** [comment]
I have a clear opinion on this: `master` is always reflecting the latest stable `release`, so after a release being published with no bigger issues we should merge it to master. All development effort is going into development and release candidates are merged into `release`. In such a case `master` remains the base branch, because it reflects the latest production-stable version, no matter what mess has been created on other branches and this is why I think it should be push-protected.

**Comment by jankapunkt** [comment]
@HappyZombies I added a PR regarding branching and contribution guidelines and I would ask to you to work on the maintainers part a bit (which is more closely related to the branching strategy) and let me know what you think of the current state.

**Comment by jwerre** [comment]
I'm also a fan of:

- mocha, chai or should
- eslint
- jsdocs

**Comment by jankapunkt** [comment]
@jwerre good thing is that current tests already use mocha and chai so there is not much to change on their side. I already added NYC for coverage in 10 min or so

**Comment by jwerre** [comment]
I just realized the `should.js` is the main the assertion library but the repo has been archived! I wonder if continuing to use it would be the best way to future-proof. What do you guys think?  Do you think we could just use Chai's [should interface](https://www.chaijs.com/guide/styles/#should) as a simple swap in replacement. e.g.:

```js
// var should = require('should'); // old way
const should = require('chai').should()
```
What a lot of people don't like about should is that it extends the `Object.prototype`. I've used `should` for years and never had any problem but I get the complaint. That said it could be a lot of work change all the tests.

**Comment by jankapunkt** [comment]
I personally love the Chai asserter and I think together with Mocha it has the widest spread of expertise so many people should be familiar with it (yes very meta).

I think we should focus on this before we do the other issues because this is a fundamental thing for our CI and future contributions

**Comment by jwerre** [comment]
I don't think you'd need to rewrite anything if you just use Chai's should interface. I'll check it out now and see what happens.

**Comment by jwerre** [comment]
I just did a find for `should = require('should');` and replace with `should = require('chai').should()` in the entire `test/unit` directory and all but one test passed.

**Comment by jwerre** [comment]
Are we going to move forward with [ESLint](https://eslint.org/)? Perhaps we should start a new issue for this topic and discuss  [configuration](https://eslint.org/docs/user-guide/configuring/)?

**Comment by HappyZombies** [comment]
I think we should go for ESLint, I thought about prettier, but having it find code errors will help us catch those undefined errors quickly.

In the original project, they started using ESLint but, never got merged to master. Perhaps this is something we can benefit from? 

https://github.com/oauthjs/node-oauth2-server/blob/dev/.eslintrc

**Comment by jankapunkt** [comment]
I agree let's create a separate issue and discuss a potential eslint config

**Comment by jankapunkt** [comment]
@HappyZombies there should be a setting somewhere that pull requests need approval

**Comment by HappyZombies** [comment]
@jwerre let's take the Node version convo to #34

**Comment by Uzlopak** [comment]
Also i want to mention that the integration tests are imho basically pointless. 

Currently everything is mocked with pointless stubs. How you want to check if the scope is valid, if the method always returns a specified return value. 

It would be better to implement an in memory model. And write unit tests which check the correct behavior of the memory model and then run tests against it. Thus showing us some real issues.

**Comment by HappyZombies** [comment]
Closing this issue as other individual items have been made and I believe we have addressed all we could here.
