### ISSUE TITLE
Modernize code to ES6+

### ISSUE THREAD

**Issue by jankapunkt** [node-oauth/node-oauth2-server#54]
I think we have a huge potential to transform as many variables as possible to `const` and `let` which allows us to have better scoping (block-scoped variables) and let's us detect unintended mutations early.

We already replaced many lodash functions with native ES6 alternatives so I think it might be good to consequentially do this for the rest of the code, too.

This issue is weakly related to #48

**Comment by HappyZombies** [comment]
@jankapunkt is there any other place we need to update for ES6+? If not we can close this item :)
