### ISSUE TITLE
Make is.js it's own independent module

### ISSUE THREAD

**Issue by jwerre** [node-oauth/node-oauth2-server#55]
[is.js](https://github.com/node-oauth/node-oauth2-server/blob/master/lib/validator/is.js) really slows down the tests. What do you guys think about moving it to it's own repository and adding it as a dependency?

<img width="1028" alt="Screen Shot 2021-11-10 at 8 42 09 AM" src="https://user-images.githubusercontent.com/747587/141144881-cc8d6604-e235-40e0-b8f2-ce9ce37f0435.png">

**Comment by jankapunkt** [comment]
Hey @jwerre this code was written by me when I added these tests. The thing is, that the RegEx that is about to be tested allows nearly the whole unicode set and I do lots of permutations in order to cover them. This is course takes lot of time.

From my pov we should not remove them but we could update the docs and describe why this test is so slow (and give some background info).

We can also add an instant remedy by describing how to use regex pattern to filter out mocha tests that are not of focus right now: https://mochajs.org/#-grep-regexp-g-regexp

What do you think?

**Comment by jwerre** [comment]
@jankapunkt Yes I remember when you wrote these test. Nice work by the way—I agree with you that they were needed. I guess I'm not clear why you wouldn't want to add `is.js` as a dependance under the same organization. It's not really oauth specific, it's not likely to change, and it would shave 5.5 sec off the unit tests. It just doesn't make sense to run these tests with every deployment of `node-oauth-server` when they can be run independently whenever there are changes to is.js.

**Comment by jankapunkt** [comment]
Ah now I get, you want to add them as internal dependency. We could do this.

**Comment by jankapunkt** [comment]
@jwerre @HappyZombies I would start this as a new repo under this org if you both agree

**Comment by jwerre** [comment]
I put `is.js` into it's on [repo](https://github.com/node-oauth/is-unicode). @HappyZombies would you mind publishing this to NPM? Once that's done I'll update the code and create a PR. @jankapunkt feel free to clone and make any changes you see fit.

**Comment by jankapunkt** [comment]
@jwerre @HappyZombies I would first make some additions, like adding the namespace, updating the README, link the RFC docs etc. I'll link the PR here

**Comment by jankapunkt** [comment]
See https://github.com/node-oauth/is-unicode/pull/1

**Comment by Uzlopak** [comment]
I am sorry to be nagging on the wording, but I think the name is wrong. it is not a "is-unicode"  package because some of the validators are not unicode but simple ascii. It is actually something like oauth2-formats (naming similar to something like ajv-formats).

**Comment by jankapunkt** [comment]
@jwerre what do you think about renaming? It's at least not published, yet.

**Comment by jwerre** [comment]
Yes! Good call @Uzlopak

**Comment by jankapunkt** [comment]
I will rename and then publish, so we can finally integrate it :-)

**Comment by jankapunkt** [comment]
Published 1.0.0: https://www.npmjs.com/package/@node-oauth/formats
Let's keep this open until we integrated it into the main package

**Comment by jorenvandeweyer** [comment]
Resolved by #108
