### ISSUE TITLE
SonarQube: Control Character in UNICODECHARNOCRLF in is.js

### ISSUE THREAD

**Issue by Uzlopak** [node-oauth/node-oauth2-server#62]
SonarQube remarks that it is most likely that the Control Character \u0009 is a bug. 

0x9 is Tab-Control Character. 

is.uchar is used in password-grant-type.js for validating the content of username and password. 

The question here is: Is it possible to have Tab as a character of a username and/or password? I say: No

I think this is a valid finding. 

I recommend to remove the Tab-Control-Character.

Lets Discuss.

**Comment by jankapunkt** [comment]
I would keep, since we should not define password requirements and neither does the standard but I will check again what the standard says to be sure on that.

**Comment by Uzlopak** [comment]
@jankapunkt 

you are right. 

https://datatracker.ietf.org/doc/html/rfc6749#appendix-A

```
Appendix A.  Augmented Backus-Naur Form (ABNF) Syntax

   This section provides Augmented Backus-Naur Form (ABNF) syntax
   descriptions for the elements defined in this specification using the
   notation of [RFC5234].  The ABNF below is defined in terms of Unicode
   code points [W3C.REC-xml-20081126]; these characters are typically
   encoded in UTF-8.  Elements are presented in the order first defined.

   Some of the definitions that follow use the "URI-reference"
   definition from [RFC3986].

   Some of the definitions that follow use these common definitions:

     VSCHAR     = %x20-7E
     NQCHAR     = %x21 / %x23-5B / %x5D-7E
     NQSCHAR    = %x20-21 / %x23-5B / %x5D-7E
     UNICODECHARNOCRLF = %x09 /%x20-7E / %x80-D7FF /
                         %xE000-FFFD / %x10000-10FFFF

   (The UNICODECHARNOCRLF definition is based upon the Char definition
   in Section 2.2 of [W3C.REC-xml-20081126], but omitting the Carriage
   Return and Linefeed characters.)
```
