### ISSUE TITLE
Don't repeat tests when they fail.

### ISSUE THREAD

**Issue by jwerre** [node-oauth/node-oauth2-server#68]
Let's change this to 0... why repeat failed tests?

https://github.com/node-oauth/node-oauth2-server/blob/485147fb156310527456e06da41780b188cf2ca1/.mocharc.yml#L3

**Comment by jankapunkt** [comment]
Yes you are right, fail early fail often

**Comment by jankapunkt** [comment]
@jwerre did you leave the project? I just wanted to mention you in another PR and found, that you are not in the team list anymore :eyes:

**Comment by jwerre** [comment]
Ya, sorry guys... I mentioned it in the Discord. I wish I had more time to work on this I'm pretty busy these days. :(

**Comment by jankapunkt** [comment]
Ah I see thanks for all your contribution so far I think we already did a great move! There is one open PR #107  of yours, I would pick it up and finish if you are okay with it

**Comment by jwerre** [comment]
Yes please do.

**Comment by jorenvandeweyer** [comment]
Already fixed.
