### ISSUE TITLE
Conformance tests

### ISSUE THREAD

**Issue by Uzlopak** [node-oauth/node-oauth2-server#73]
Maybe there is something useful here https://www.certification.openid.net/

Seems actually be OIDC specific. But maybe there is something we could use.

**Comment by HappyZombies** [comment]
I am not quiet sure what this is, is it a demo?

**Comment by HappyZombies** [comment]
Oh nvm I see the info about this here https://openid.net/certification/about-conformance-suite/

**Comment by jankapunkt** [comment]
If we can get this running locally somehow in a reproducible way we can integrate this into our CI and run this, for example, on `release-*` branches.

**Comment by jorenvandeweyer** [comment]
I'm closing this issue. 

Based on #79 I conclude that we can't test this directly on the library it self. We also have an open issue that covers security (#65).
