### ISSUE TITLE
Implement PKCE

### ISSUE THREAD

**Issue by Uzlopak** [node-oauth/node-oauth2-server#76]
See https://snyk.io/vuln/npm:oauth2-server
https://github.com/oauthjs/node-oauth2-server/pull/452

**Comment by jankapunkt** [comment]
Related: [rfc7636](https://datatracker.ietf.org/doc/html/rfc7636)

**Comment by jankapunkt** [comment]
I started this here: #86

**Comment by FStefanni** [comment]
Hi,

if can be of any help, this is the full list of pr related to PKCE, in the original project:

* https://github.com/oauthjs/node-oauth2-server/pull/452
* https://github.com/oauthjs/node-oauth2-server/pull/658
* https://github.com/oauthjs/node-oauth2-server/pull/659

Regards.

**Comment by nekman** [comment]
This issue is labeled with high priority. However, it have been open for 10 months. When do you plan to release this? Or must all issues in the v4.3 milestone be completed first? I don't want to stress anything, just would like to have this feature in the library 👍

**Comment by jankapunkt** [comment]
Hi @nekman as I stated a few times, we need more people to test this with a real world setup. Just a few days ago someone did and revealed a missing feature which is now added as another PR. 

If you want to get this feature faster merged then please help out with testing.

I have limited resources as I have only the authorization code workflow as setup to test. The other workflows can only be tested by me locally in an artificial environment.

You can also help out by reviewing existing pull requests regarding PKCE.

I will also try to get this repo into Hacktonerfest (never did this but I see some potential for getting some support).

**Comment by nekman** [comment]
Thanks for the information @jankapunkt. Of course we should not stress anything. Important to get it right and well tested. I will see what I can do!

**Comment by jankapunkt** [comment]
implemented in 4.3.0 by PR #86
