### ISSUE TITLE
Maintaining adapter packages?

### ISSUE THREAD

**Issue by jankapunkt** [node-oauth/node-oauth2-server#8]
Do we want to maintain adapters under this org, too? At least for express I can provide support. One argument for it is, that it will build much more trust and we can ensure this will live on. Argument against is that we have more to maintain overall.

**Comment by jankapunkt** [comment]
Another advantage would be to have CI runninng integration tests before publishing releases, e.g. when merging into a `release` branch

**Comment by HappyZombies** [comment]
I think we should, but let's see how this project goes first. If we gain traction and are putting out releases, we can start taking in other adapter packages too.

**Comment by jwerre** [comment]
I agree, in fact I've already written an adapter to express which I'd be happy to push.

**Comment by HappyZombies** [comment]
I am ok with the number of maintainers currently, besides like I mentioned we should put a small hold on adding all adapters and what not, we still have administrator stuff to do and whatever else small bug fixes.

I think us three can handle it right now, if it becomes too much we can add more maintainers to handle the adapters and example project(s).
