### ISSUE TITLE
Solving appropriate the Client Side RefreshToken Race Issue

### ISSUE THREAD

**Issue by Uzlopak** [node-oauth/node-oauth2-server#80]
I wrote a very nice text and now I am just sad because my Chrome freeze and every well formulated word is gone.

So again...but shorter

In native applications we dont have a Race Condition when refreshing a Access Token. But in a Browser-App we have the issue, that we will use multiple Tabs. So if an Access Token expires or is going to expire, all the Tabs start to Refresh the Token. Even if we use one central datastore (cookiestore, localStorage). I once solved this by allowing the creation of multiple access token by one refresh token and disabling Refresh Token Rotation. 

But this is actually an Anti-Pattern. 

So I thought how we can implement it in a save and stable way:

I think the desired behavior is that in a specific and very very short timeframe the RefreshToken can be used multiple times but MUST return always the same AccessToken. So I propose to add an option next to alwaysIssueNewRefreshToken named refreshTokenExpirationDelay (name pending). 

It works like this: 

1. Clients in Browser realize that their Access Token is going to expire and each one of the start the refreshToken Grant
2. Authorization Server does the usual validation stuff
3. New Access Token and new Refresh Token (alwaysIssueNewRefreshToken is set) are generated
4. old RefreshToken gets the value or a reference of the new Access Token, the value or the reference of the new Refresh Token and the expiration of the old RefreshToken is set to now + refreshTokenExpirationDelay (now + 5000 => 5 seconds in the future), but with the condition that it will only set those fields if the new AccessToken value or reference was not set before.
5. Check if our DB Operation in step 4 changed an entry or not
5.1 We successfully changed old Refresh Token => we won the race. 
5.2 We did not change anything. Load the new Access Token and the new RefreshToken from the Database and delete the unnecessary generated Access and Refresh Token in Step 3
6. Return new AccessToken and RefreshToken

Any Optimizations you would suggest?

This would be possible breaking the saveToken-method in the Model.

**Comment by Uzlopak** [comment]
See also
https://hackerone.com/reports/55140

The refreshTokenExpirationDelay could be named alwaysIssueNewRefreshTokenGracePeriod

**Comment by jorenvandeweyer** [comment]
The library already handles this issue if the user implements the revokeToken function correctly.

https://github.com/node-oauth/node-oauth2-server/blob/f46037154cc2bc4197c757f7a10ac6874a65dffc/lib/grant-types/refresh-token-grant-type.js#L45-L59

https://github.com/node-oauth/node-oauth2-server/blob/f46037154cc2bc4197c757f7a10ac6874a65dffc/lib/grant-types/refresh-token-grant-type.js#L114-L118

As you can see in the code snippets above, when the function `revokeToken` of the model fails, the whole refresh call fails.

This is already included in the docs:

https://github.com/node-oauth/node-oauth2-server/blob/f46037154cc2bc4197c757f7a10ac6874a65dffc/docs/model/spec.rst?plain=1#L778-L781
