### ISSUE TITLE
Feel free to join our Discord for live chatting

### ISSUE THREAD

**Issue by HappyZombies** [node-oauth/node-oauth2-server#85]
https://discord.gg/4HTUAcTvqV

The Discord is not a replacement for the issue board, please do not use the discord for bug reporting.

**Comment by jankapunkt** [comment]
@HappyZombies should we shutdown the discord? No one is really replying and there is not much activity. I also don't check discord that often.

**Comment by HappyZombies** [comment]
Yeah I Think we can just keep conversations here or even use the discussions
