### ISSUE TITLE
Add sha512sum to package.json

### ISSUE THREAD

**Issue by jankapunkt** [node-oauth/node-oauth2-server#95]
To improve trust I thought we may add the sha512sum (the one which is added during npm pubklish to the package.json) to every commit or at least every commit that is used when publishing a new version.

Alternatively, is there a better or more "best practice" way to give people the chance to easily (accessible) verify the packge's code integrity with the code on GitHub?

**Comment by HappyZombies** [comment]
@jankapunkt This is something I haven't done before. I am down with this, but what would this look like?

**Comment by jorenvandeweyer** [comment]
@jankapunkt Is this something we still want to do?

**Comment by jankapunkt** [comment]
I think this is really just nice 2 have, I'm closing this
